from .. .models import Airport, AirportSchema, Journey, JourneySchema, db
from datetime import datetime, timedelta

airport_schema = AirportSchema()
journey_schema = JourneySchema()


def routeInsertionCommands():
    db.session.add(Journey('AEP', 'Argentina', 'AFA', 'Argentina', 10, datetime.utcnow(), datetime.utcnow()+ timedelta(days=30)))
    db.session.add(Journey('AEP', 'Argentina', 'AFA', 'Argentina', 10, datetime.utcnow()+ timedelta(days=30), datetime.utcnow()+ timedelta(days=60)))
    db.session.add(Journey('AGT', 'Paraguay', 'ANF', 'Chile', 20, datetime.utcnow(), datetime.utcnow()+ timedelta(days=30)))
    db.session.add(Journey('AOL', 'Argentina', 'ARN', 'Suecia', 30, datetime.utcnow()+ timedelta(days=30), datetime.utcnow()+ timedelta(days=60)))
    db.session.add(Journey('ATH', 'Grecia', 'HAJ', 'Alemania', 40, datetime.utcnow(), datetime.utcnow()+ timedelta(days=30)))
    db.session.add(Journey('BSL', 'Francia', 'BYJ', 'Portugal', 50, datetime.utcnow()+ timedelta(days=30), datetime.utcnow()+ timedelta(days=60)))
    db.session.commit()
'''
    id = db.Column(db.Integer, primary_key=True)
    sourceAirportCode = db.Column(db.String(10), unique=False, nullable=False)
    sourceCountry = db.Column(db.String(80), unique=False, nullable=False)
    destinyAirportCode = db.Column(db.String(10), unique=False, nullable=False)
    destinyCountry = db.Column(db.String(80), unique=False, nullable=False)
    bagCost = db.Column(db.Integer)
    createdAt = db.Column(db.DateTime, default=datetime.utcnow)
    
    datetime.utcnow() + timedelta(days=1)
'''


def airportInsertionCommands():
    db.session.add(Airport('ABC', 'Aeropuerto de Albacete', 'Albacete', 'Castilla La Mancha', 'España'))
    db.session.add(Airport('AEP', 'Aeroparque Jorge Newbery', 'Buenos Aires', 'Buenos Aires', 'Argentina'))
    db.session.add(Airport('AFA', 'Aeropuerto Internacional Suboficial Ayudante Santiago Germano', 'San Rafael', 'Mendoza', 'Argentina'))
    db.session.add(Airport('AGP', 'Aeropuerto de Málaga-Costa del Sol', 'Málaga', 'Andalucía', 'España'))
    db.session.add(Airport('AGT', 'Aeropuerto Internacional Guaraní', 'Ciudad del Este', 'Alto Paraná', 'Paraguay'))
    db.session.add(Airport('AMS', 'Aeropuerto de Ámsterdam-Schiphol', 'Ámsterdam', 'Holanda Septentrional', 'Países Bajos'))
    db.session.add(Airport('ANF', 'Aeropuerto Andrés Sabella', 'Antofagasta', 'Antofagasta', 'Chile'))
    db.session.add(Airport('AOL', 'Aeropuerto Internacional de Paso de los Libres', 'Paso de los Libres', 'Corrientes', 'Argentina'))
    db.session.add(Airport('ARI', 'Aeropuerto Internacional Chacalluta', 'Arica', 'Arica y Parinacota', 'Chile'))
    db.session.add(Airport('ARN', 'Aeropuerto de Estocolmo-Arlanda', 'Estocolmo', 'Estocolmo', 'Suecia'))
    db.session.add(Airport('ASU', 'Aeropuerto Internacional Silvio Pettirossi', 'Asunción', 'Central', 'Paraguay'))
    db.session.add(Airport('ATH', 'Aeropuerto Internacional Eleftherios Venizelos', 'Atenas', 'Ática', 'Grecia'))
    db.session.add(Airport('AUA', 'Aeropuerto Internacional Reina Beatrix', 'Oranjestad', 'Aruba', 'Países Bajos'))
    db.session.add(Airport('BBA', 'Aeródromo Balmaceda', 'Balmaceda', 'Aysén', 'Chile'))
    db.session.add(Airport('BCN', 'Aeropuerto de Barcelona-El Prat', 'Barcelona', 'Cataluña', 'España'))
    db.session.add(Airport('BIN', 'Aeropuerto de Bamiyán', 'Bamiyán', 'Provincia de Bamiyán', 'Afganistán'))
    db.session.add(Airport('BIO', 'Aeropuerto de Bilbao', 'Bilbao', 'Vizcaya', 'España'))
    db.session.add(Airport('BOD', 'Aeropuerto de Burdeos-Mérignac', 'Burdeos', 'Aquitania', 'Francia'))
    db.session.add(Airport('BOG', 'Aeropuerto Internacional El Dorado', 'Bogotá', 'Bogotá, D. C.', 'Colombia'))
    db.session.add(Airport('BPM', 'Base Aérea de Bagram', 'Bagram', 'Provincia de Parwan', 'Afganistán'))
    db.session.add(Airport('BRC', 'Aeropuerto Internacional Teniente Luis Candelaria', 'San Carlos de Bariloche', 'Río Negro', 'Argentina'))
    db.session.add(Airport('BSL', 'Aeropuerto de Basilea-Mulhouse-Friburgo', 'Basilea, Mulhouse, Friburgo', 'Alsacia', 'Francia'))
    db.session.add(Airport('BST', 'Aeropuerto de Bost', 'Lashkar Gah', 'Provincia de Helmand', 'Afganistán'))
    db.session.add(Airport('BUD', 'Aeropuerto de Budapest-Ferenc Liszt', 'Budapest', 'Budapest', 'Hungría'))
    db.session.add(Airport('BYJ', 'Base Aérea de Beja', 'Beja', 'Alentejo', 'Portugal'))
    db.session.add(Airport('COR', 'Aeropuerto Internacional Ing. Ambrosio Taravella', 'Córdoba', 'Córdoba', 'Argentina'))
    db.session.add(Airport('CDT', 'Aeropuerto de Castellon', 'Castellon', 'Comunidad Valenciana', 'España'))
    db.session.add(Airport('CCC', 'Aeropuerto Internacional de Jardines del Rey', 'Cayo Coco', 'Ciego de Ávila', 'Cuba'))
    db.session.add(Airport('CCP', 'Aeropuerto Carriel Sur', 'Concepción', 'Biobío', 'Chile'))
    db.session.add(Airport('CCS', 'Aeropuerto Internacional de Maiquetía Simón Bolívar', 'Caracas', 'Dependencias Federales', 'Venezuela'))
    db.session.add(Airport('CDG', 'Aeropuerto de París-Charles de Gaulle', 'París', 'Isla de Francia', 'Francia'))
    db.session.add(Airport('CGN', 'Aeropuerto Internacional de Colonia/Bonn Konrad Adenauer', 'Colonia, Bonn', 'Renania del Norte-Westfalia', 'Alemania'))
    db.session.add(Airport('CLO', 'Aeropuerto Internacional Bonilla Aragón', 'Cali', 'Valle del cauca', 'Colombia'))
    db.session.add(Airport('CLX', 'Aeropuerto Clorinda', 'Clorinda', 'Formosa', 'Argentina'))
    db.session.add(Airport('CMN', 'Aeropuerto Internacional Mohammed V', 'Casablanca', 'Región de Casablanca-Settat', 'Marruecos'))
    db.session.add(Airport('CNQ', 'Aeropuerto Internacional Doctor Fernando Piragine Niveyro', 'Ciudad de Corrientes', 'Corrientes', 'Argentina'))
    db.session.add(Airport('COC', 'Aeropuerto Comodoro Pierrestegui', 'Concordia', 'Entre Ríos', 'Argentina'))
    db.session.add(Airport('CTC', 'Aeropuerto Coronel Felipe Varela', 'San Fernando del Valle de Catamarca', 'Catamarca', 'Argentina'))
    db.session.add(Airport('CUE', 'Aeropuerto Internacional Mariscal Lamar', 'Cuenca', 'Azuay', 'Ecuador'))
    db.session.add(Airport('CUU', 'Aeropuerto Internacional General Roberto Fierro Villalobos', 'Chihuahua', 'Chihuahua', 'México'))
    db.session.add(Airport('CVU', 'Aeropuerto de Corvo', 'Isla de Corvo', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('CWB', 'Aeropuerto Internacional Afonso Pena', 'Curitiba', 'BRA BRA', 'Brasil'))
    db.session.add(Airport('DAY', 'Aeropuerto Internacional James M. Cox-Dayton', 'Dayton', 'Ohio', 'Estados Unidos'))
    db.session.add(Airport('DJE', 'Aeropuerto Internacional de Yerba-Zarzis', 'Yerba', 'Medenine', 'Túnez'))
    db.session.add(Airport('DME', 'Aeropuerto Internacional de Moscú-Domodédovo', 'Moscú', 'Óblast de Moscú', 'Rusia'))
    db.session.add(Airport('DOH', 'Aeropuerto Internacional Hamad', 'Doha', 'Municipio de Doha', 'Catar'))
    db.session.add(Airport('DXB', 'Aeropuerto Internacional de Dubái', 'Dubái', 'Dubái', 'Emiratos Árabes Unidos'))
    db.session.add(Airport('EAP', 'Aeropuerto de Basilea-Mulhouse-Friburgo', 'Basilea, Mulhouse, Friburgo', 'Alsacia', 'Francia'))
    db.session.add(Airport('EDI', 'Aeropuerto de Edimburgo', 'Edimburgo', 'Escocia', 'Reino Unido'))
    db.session.add(Airport('EGE', 'Aeropuerto Regional del Condado de Eagle', 'Eagle-Vail', 'Colorado', 'Estados Unidos'))
    db.session.add(Airport('EIN', 'Aeropuerto de Eindhoven', 'Eindhoven', 'Brabante Septentrional', 'Países Bajos'))
    db.session.add(Airport('EPA', 'Aeropuerto El Palomar', 'Área metropolitana de Buenos Aires', 'Buenos Aires', 'Argentina'))
    db.session.add(Airport('ESR', 'Aeródromo Ricardo García Posada', 'El Salvador (Chile)', 'Atacama', 'Chile'))
    db.session.add(Airport('EZE', 'Aeropuerto Internacional Ministro Pistarini', 'Ezeiza', 'Buenos Aires', 'Argentina'))
    db.session.add(Airport('ENO', 'Aeropuerto Teniente Amín Ayub González', 'Encarnacion (Paraguay)', 'Itapúa', 'Paraguay'))
    db.session.add(Airport('FAO', 'Aeropuerto de Faro', 'Faro', 'Algarve', 'Portugal'))
    db.session.add(Airport('FBD', 'Aeropuerto de Fayzabad', 'Fayzabad', 'Provincia de Badajshan', 'Afganistán'))
    db.session.add(Airport('FCO', 'Aeropuerto de Roma-Fiumicino', 'Roma', 'Lacio', 'Italia'))
    db.session.add(Airport('FDO', 'Aeropuerto Internacional de San Fernando', 'San Fernando', 'Buenos Aires', 'Argentina'))
    db.session.add(Airport('FLR', 'Aeropuerto de Florencia', 'Florencia', 'Toscana', 'Italia'))
    db.session.add(Airport('FLW', 'Aeropuerto de Flores', 'Isla de Flores', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('FMA', 'Aeropuerto Internacional de Formosa', 'Ciudad de Formosa', 'Formosa', 'Argentina'))
    db.session.add(Airport('FNC', 'Aeropuerto Internacional Cristiano Ronaldo', 'Funchal', 'Madeira', 'Portugal'))
    db.session.add(Airport('FRA', 'Aeropuerto de Fráncfort del Meno', 'Fráncfort del Meno', 'Hesse', 'Alemania'))
    db.session.add(Airport('FRS', 'Aeropuerto Internacional Mundo Maya', 'Santa Elena de la Cruz', 'Petén', 'Guatemala'))
    db.session.add(Airport('FOR', 'Aeropuerto Internacional Pinto Martins', 'Fortaleza', 'Ceará', 'Brasil'))
    db.session.add(Airport('FTE', 'Aeropuerto Internacional Comandante Armando Tola', 'El Calafate', 'Santa Cruz', 'Argentina'))
    db.session.add(Airport('GDL', 'Aeropuerto Internacional de Guadalajara', 'Guadalajara, Jalisco', 'Jalisco', 'México'))
    db.session.add(Airport('GHU', 'Aeropuerto de Gualeguaychú', 'Gualeguaychú', 'Entre Ríos', 'Argentina'))
    db.session.add(Airport('GIB', 'Aeropuerto de Gibraltar', 'Gibraltar', 'Gibraltar', 'Reino Unido'))
    db.session.add(Airport('GPO', 'Aeropuerto de General Pico', 'General Pico', 'La Pampa', 'Argentina'))
    db.session.add(Airport('GRU', 'Aeropuerto Internacional de São Paulo-Guarulhos', 'São Paulo', 'São Paulo', 'Brasil'))
    db.session.add(Airport('GRW', 'Aeropuerto de Graciosa', 'Isla Graciosa', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('GRX', 'Aeropuerto de Granada', 'Granada', 'Andalucía', 'España'))
    db.session.add(Airport('GUA', 'Aeropuerto Internacional La Aurora', 'Ciudad de Guatemala', 'Guatemala', 'Guatemala'))
    db.session.add(Airport('GYE', 'Aeropuerto Internacional Jose Joaquin de Olmedo', 'Guayaquil', 'Guayas', 'Ecuador'))
    db.session.add(Airport('HAJ', 'Aeropuerto de Hannover', 'Hannover', 'Baja Sajonia', 'Alemania'))
    db.session.add(Airport('HAM', 'Aeropuerto de Hamburgo', 'Hamburgo', 'Hamburgo', 'Alemania'))
    db.session.add(Airport('HAV', 'Aeropuerto Internacional José Martí', 'La Habana', 'La Habana', 'Cuba'))
    db.session.add(Airport('HBX', 'Aeropuerto de Hubli', 'Hubballi, Dharwad', 'Karnataka', 'India'))
    db.session.add(Airport('HEA', 'Aeropuerto de Herat', 'Herat', 'Provincia de Herat', 'Afganistán'))
    db.session.add(Airport('HEL', 'Aeropuerto de Helsinki-Vantaa', 'Helsinki', 'Uusimaa', 'Finlandia'))
    db.session.add(Airport('HGL', 'Aeropuerto de Heligoland', 'Heligoland', 'Schleswig-Holstein', 'Alemania'))
    db.session.add(Airport('HHN', 'Aeropuerto de Fráncfort-Hahn', 'Fráncfort', 'Renania del Norte-Westfalia', 'Alemania'))
    db.session.add(Airport('HIR', 'Aeropuerto Internacional de Honiara', 'Honiara', 'Honiara', 'Islas Salomón'))
    db.session.add(Airport('HKG', 'Aeropuerto Internacional de Hong Kong', 'Hong Kong', 'Región Administrativa Especial de Hong Kong', 'China'))
    db.session.add(Airport('HMO', 'Aeropuerto Internacional General Ignacio Pesqueira García', 'Hermosillo', 'Sonora', 'México'))
    db.session.add(Airport('HND', 'Aeropuerto Internacional de Haneda', 'Tokio', 'Tokio', 'Japón'))
    db.session.add(Airport('HOG', 'Aeropuerto Internacional Frank País', 'Holguín', 'Holguín', 'Cuba'))
    db.session.add(Airport('HOR', 'Aeropuerto de Horta', 'Isla de Faial', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('HNL', 'Aeropuerto Internacional de Honolulu', 'Honolulu', 'Hawái', 'Estados Unidos'))
    db.session.add(Airport('HOU', 'Aeropuerto William P. Hobby', 'Houston', 'Texas', 'Estados Unidos'))
    db.session.add(Airport('IBZ', 'Aeropuerto de Ibiza', 'Ibiza', 'Islas Baleares', 'España'))
    db.session.add(Airport('ICN', 'Aeropuerto Internacional de Incheon', 'Incheon, Seúl', 'Ciudad Metropolitana de Incheon', 'Corea del Sur'))
    db.session.add(Airport('IGR', 'Aeropuerto Internacional de Puerto Iguazú', 'Puerto Iguazú', 'Provincia de Misiones', 'Argentina'))
    db.session.add(Airport('INV', 'Aeropuerto de Inverness', 'Inverness', 'Escocia', 'Reino Unido'))
    db.session.add(Airport('IPC', 'Aeropuerto Internacional Mataveri', 'Isla de Pascua', 'Valparaíso', 'Chile'))
    db.session.add(Airport('IQQ', 'Aeropuerto Internacional Diego Aracena', 'Iquique', 'Tarapacá', 'Chile'))
    db.session.add(Airport('IRJ', 'Aeropuerto Capitán Vicente Almandos Almonacid', 'Ciudad de La Rioja', 'La Rioja', 'Argentina'))
    db.session.add(Airport('IST', 'Aeropuerto Internacional Atatürk', 'Estambul', 'Provincia de Estambul', 'Turquía'))
    db.session.add(Airport('IVL', 'Aeropuerto de Ivalo', 'Ivalo', 'Laponia Finlandesa', 'Finlandia'))
    db.session.add(Airport('JAA', 'Aeropuerto de Jalalabad', 'Jalalabad', 'Provincia de Nangar', 'Afganistán'))
    db.session.add(Airport('JER', 'Aeropuerto de Jersey', 'Saint Helier', 'Jersey', 'Reino Unido'))
    db.session.add(Airport('JFK', 'Aeropuerto Internacional John F. Kennedy', 'Nueva York', 'Nueva York', 'Estados Unidos'))
    db.session.add(Airport('JKL', 'Aeropuerto Nacional de Kálimnos', 'Pothia (en)', 'Egeo Meridional', 'Grecia'))
    db.session.add(Airport('JSR', 'Aeropuerto de Jessore', 'Jessore (en)', 'Khulna', 'Bangladés'))
    db.session.add(Airport('JUJ', 'Aeropuerto Internacional Gobernador Horacio Guzmán', 'San Salvador de Jujuy', 'Provincia de Jujuy', 'Argentina'))
    db.session.add(Airport('KBL', 'Aeropuerto Internacional de Kabul', 'Kabul', 'Provincia de Kabul', 'Afganistán'))
    db.session.add(Airport('KDH', 'Aeropuerto Internacional de Kandahar', 'Kandahar', 'Provincia de Kandahar', 'Afganistán'))
    db.session.add(Airport('KEF', 'Aeropuerto Internacional de Keflavík', 'Reikiavik', 'Höfuðborgarsvæðið', 'Islandia'))
    db.session.add(Airport('KGD', 'Aeropuerto de Kaliningrado-Jrabrovo', 'Kaliningrado', 'Óblast de Kaliningrado', 'Rusia'))
    db.session.add(Airport('LAD', 'Aeropuerto Internacional Quatro de Fevereiro', 'Luanda', 'Provincia de Luanda', 'Angola'))
    db.session.add(Airport('LAS', 'Las Vegas, Mc Carran International Airport', 'Las Vegas', 'Nevada', 'Estados Unidos'))
    db.session.add(Airport('LAX', 'Aeropuerto Internacional de Los Ángeles', 'Los Ángeles', 'California', 'Estados Unidos'))
    db.session.add(Airport('LCE', 'Aeropuerto Internacional Golosón', 'La Ceiba', 'Atlántida', 'Honduras'))
    db.session.add(Airport('LEI', 'Aeropuerto de Almería', 'Almería', 'Andalucía', 'España'))
    db.session.add(Airport('LEU', 'Aeropuerto de Andorra-La Seu',"La Seu d'Urgell, Andorra la Vella",'Cataluña', 'España'))
    db.session.add(Airport('LGG', 'Aeropuerto de Lieja', 'Lieja', 'Región Valona', 'Bélgica'))
    db.session.add(Airport('LGS', 'Aeropuerto Internacional Comodoro Ricardo Salomón', 'Malargüe', 'Mendoza', 'Argentina'))
    db.session.add(Airport('LGW', 'Aeropuerto de Gatwick', 'Londres', 'Inglaterra', 'Reino Unido'))
    db.session.add(Airport('LHR', 'Aeropuerto de Heathrow', 'Londres', 'Inglaterra', 'Reino Unido'))
    db.session.add(Airport('LIM', 'Aeropuerto Internacional Jorge Chávez', 'Lima, Callao.', 'Callao', 'Perú'))
    db.session.add(Airport('LIR', 'Guanacaste Aeropuerto', 'Guanacaste', 'Guanacaste', 'Costa Rica'))
    db.session.add(Airport('LIS', 'Aeropuerto de Portela', 'Lisboa', 'Lisboa', 'Portugal'))
    db.session.add(Airport('LTN', 'Aeropuerto de Londres-Luton', 'Londres', 'Inglaterra', 'Reino Unido'))
    db.session.add(Airport('LUQ', 'Aeropuerto Brigadier Mayor César Raúl Ojeda', 'Ciudad de San Luis', 'San Luis', 'Argentina'))
    db.session.add(Airport('MAD', 'Aeropuerto Adolfo Suárez Madrid-Barajas', 'Madrid', 'Comunidad de Madrid', 'España'))
    db.session.add(Airport('MCS', 'Aeropuerto de Monte Caseros', 'Monte Caseros', 'Corrientes', 'Argentina'))
    db.session.add(Airport('MDE', 'Aeropuerto Internacional José María Cordova', 'Rionegro, Medellín', 'Antioquia', 'Colombia'))
    db.session.add(Airport('MDQ', 'Aeropuerto Internacional Astor Piazzolla', 'Mar del Plata', 'Buenos Aires', 'Argentina'))
    db.session.add(Airport('MVD', 'Aeropuerto Internacional de Carrasco', 'Montevideo', 'Montevideo', 'Uruguay'))
    db.session.add(Airport('MDZ', 'Aeropuerto Internacional Gobernador Francisco Gabrielli', 'Ciudad de Mendoza', 'Mendoza', 'Argentina'))
    db.session.add(Airport('MEC', 'Aeropuerto de Manta', 'Manta', 'Manabí', 'Ecuador'))
    db.session.add(Airport('MGA', 'Aeropuerto Internacional Augusto C. Sandino', 'Managua', 'Managua', 'Nicaragua'))
    db.session.add(Airport('MTY', 'Aeropuerto Internacional Mariano Escobedo', 'Monterrey', 'Castilla y León', 'México'))
    db.session.add(Airport('MEX', 'Aeropuerto Internacional Benito Juárez', 'Ciudad de México', 'México', 'México'))
    db.session.add(Airport('MDX', 'Aeropuerto del Iberá', 'Mercedes', 'Corrientes', 'Argentina'))
    db.session.add(Airport('MFM', 'Aeropuerto Internacional de Macao', 'Ciudad de Macao', 'Macao', 'China'))
    db.session.add(Airport('MIA', 'Aeropuerto Internacional de Miami', 'Miami', 'Florida', 'Estados Unidos'))
    db.session.add(Airport('MKC', 'Aeropuerto Urbano Charles B. Wheeler', 'Kansas City', 'Misuri', 'Estados Unidos'))
    db.session.add(Airport('MLH', 'Aeropuerto de Basilea-Mulhouse-Friburgo', 'Basilea, Mulhouse, Friburgo', 'Alsacia', 'Francia'))
    db.session.add(Airport('MLN', 'Aeropuerto de Melilla', 'Melilla', 'Melilla', 'España'))
    db.session.add(Airport('MPN', 'Base Aérea de Monte Agradable', 'Isla Soledad', 'Islas Malvinas', 'Reino Unido'))
    db.session.add(Airport('MUC', 'Aeropuerto Internacional de Múnich-Franz Josef Strauss', 'Munich', 'Baviera', 'Alemania'))
    db.session.add(Airport('MXP', 'Aeropuerto de Milán-Malpensa', 'Milán', 'Lombardía', 'Italia'))
    db.session.add(Airport('MZR', 'Aeropuerto de Mazar-e Sarif', 'Mazar-e Sarif', 'Provincia de Balj', 'Afganistán'))
    db.session.add(Airport('MCO', 'Orlando International Airport', 'Orlando', 'Florida', 'Estados Unidos'))
    db.session.add(Airport('NAP', 'Aeropuerto de Nápoles-Capodichino', 'Nápoles', 'Campania', 'Italia'))
    db.session.add(Airport('NIC', 'Aeropuerto de Nicosia', 'Nicosia', 'Distrito de Nicosia', 'Chipre'))
    db.session.add(Airport('NLU', 'Aeropuerto Internacional Felipe Ángeles', 'Ciudad de México', 'México', 'México'))
    db.session.add(Airport('NLK', 'Aeropuerto de la Isla Norfolk (en)', 'Kingston', 'Isla Norfolk', 'Australia'))
    db.session.add(Airport('OPO', 'Aeropuerto de Francisco Sá Carneiro', 'Oporto', 'Región Norte', 'Portugal'))
    db.session.add(Airport('ORA', 'Aero Club Orán', 'San Ramón de la Nueva Orán', 'Salta', 'Argentina'))
    db.session.add(Airport('ORD',"Aeropuerto Internacional Chicago-O'Hare",'Chicago', 'Illinois', 'Estados Unidos'))
    db.session.add(Airport('ORK', 'Aeropuerto de Cork', 'Cork', 'Munster', 'Irlanda'))
    db.session.add(Airport('ORY', 'Aeropuerto de París-Orly', 'París', 'Isla de Francia', 'Francia'))
    db.session.add(Airport('OYA', 'Aeropuerto Dr. Diego Nicolás Díaz Colodrero', 'Goya', 'Corrientes', 'Argentina'))
    db.session.add(Airport('PBR', 'Aeropuerto de Puerto Barrios “Aeropuerto Internacional La Tierra de Dios”', 'Puerto Barrios', 'Izabal', 'Guatemala'))
    db.session.add(Airport('PDP', 'Aeropuerto Internacional de Punta del Este', 'Maldonado y Punta del Este', 'Maldonado', 'Uruguay'))
    db.session.add(Airport('PDL', 'Aeropuerto João Paulo II', 'Isla de São Miguel', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('PHL', 'Aeropuerto Internacional de Filadelfia', 'Filadelfia', 'Pensilvania', 'Estados Unidos'))
    db.session.add(Airport('PIX', 'Aeropuerto de Pico', 'Isla del Pico', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('PJC', 'Aeropuerto Doctor Fuster', 'Pedro Juan Caballero (Paraguay)', 'Amambay', 'Paraguay'))
    db.session.add(Airport('PNA', 'Aeropuerto de Pamplona', 'Noáin', 'Navarra', 'España'))
    db.session.add(Airport('PRA', 'Aeropuerto General Justo José de Urquiza', 'Paraná', 'Entre Ríos', 'Argentina'))
    db.session.add(Airport('PRQ', 'Aeropuerto de Presidencia Roque Sáenz Peña', 'Presidencia Roque Sáenz Peña', 'Chaco', 'Argentina'))
    db.session.add(Airport('PSY', 'Aeropuerto de Puerto Argentino/Stanley', 'Puerto Argentino/Stanley', 'Islas Malvinas', 'Reino Unido'))
    db.session.add(Airport('PTY', 'Aeropuerto Internacional de Tocumen', 'Ciudad de Panamá', 'Provincia de Panamá', 'Panamá'))
    db.session.add(Airport('PUJ', 'Aeropuerto Internacional de Punta Cana', 'Punta Cana', 'La Altagracia', 'República Dominicana'))
    db.session.add(Airport('PUQ', 'Aeropuerto Internacional Presidente Carlos Ibáñez del Campo', 'Punta Arenas', 'Magallanes y Antártica Chilena', 'Chile'))
    db.session.add(Airport('PXO', 'Aeropuerto de Porto Santo', 'Isla de Porto Santo', 'Madeira', 'Portugal'))
    db.session.add(Airport('QGY', 'Aeropuerto Internacional de Györ-Pér', 'Györ', 'Győr-Moson-Sopron', 'Hungría'))
    db.session.add(Airport('QRC', 'Aeródromo de la Independencia',"Rancagua","O'Higgins",'Chile'))
    db.session.add(Airport('QSA', 'Aeropuerto de Sabadell', 'Sabadell', 'Cataluña', 'España'))
    db.session.add(Airport('RAK', 'Aeropuerto de Marrakech-Menara', 'Marrakech', 'Marrakech-Safí', 'Marruecos'))
    db.session.add(Airport('RBA', 'Aeropuerto de Rabat-Salé', 'Rabat', 'Rabat-Salé-Kenitra', 'Marruecos'))
    db.session.add(Airport('RES', 'Aeropuerto Internacional de Resistencia', 'Ciudad de Resistencia', 'Chaco', 'Argentina'))
    db.session.add(Airport('REU', 'Aeropuerto de Reus', 'Reus, Tarragona', 'Cataluña', 'España'))
    db.session.add(Airport('RGA', 'Aeropuerto Internacional Gob. Ramón Trejo Noel', 'Río Grande', 'Tierra del Fuego', 'Argentina'))
    db.session.add(Airport('RHD', 'Aeropuerto Internacional Termas de Río Hondo', 'Termas de Río Hondo', 'Santiago del Estero', 'Argentina'))
    db.session.add(Airport('RLO', 'Aeropuerto Internacional Valle del Conlara', 'Merlo', 'San Luis', 'Argentina'))
    db.session.add(Airport('RMU', 'Aeropuerto Internacional de la Región de Murcia', 'Región de Murcia', 'Región de Murcia', 'España'))
    db.session.add(Airport('ROS', 'Aeropuerto Internacional Rosario', 'Rosario', 'Santa Fe', 'Argentina'))
    db.session.add(Airport('RRG', 'Aeropuerto Sir Gaëtan Duval', 'Rodrigues', 'Rodrigues', 'Mauricio'))
    db.session.add(Airport('RSA', 'Aeropuerto de Santa Rosa', 'Ciudad de Santa Rosa', 'La Pampa', 'Argentina'))
    db.session.add(Airport('RUH', 'Aeropuerto Internacional Rey Khalid', 'Riad', 'Provincia de Riad', 'Arabia Saudita'))
    db.session.add(Airport('SAL', 'Aeropuerto Internacional de El Salvador San Óscar Arnulfo Romero y Galdámez', 'San Salvador', 'San Salvador', 'El Salvador'))
    db.session.add(Airport('SAP', 'Aeropuerto Internacional Ramon Villeda Morales', 'San Pedro Sula', 'Cortés', 'Honduras'))
    db.session.add(Airport('SBZ', 'Aeropuerto Internacional de Sibiu', 'Sibiu', 'Distrito de Sibiu', 'Rumania'))
    db.session.add(Airport('SCU', 'Aeropuerto Internacional Antonio Maceo y Grajales', 'Santiago de Cuba', 'Santiago de Cuba', 'Cuba'))
    db.session.add(Airport('SCL', 'Aeropuerto Internacional Arturo Merino Benítez', 'Santiago de Chile', 'Metropolitana de Santiago', 'Chile'))
    db.session.add(Airport('SDE', 'Aeropuerto Vicecomodoro Ángel de la Paz Aragonés', 'Ciudad de Santiago del Estero', 'Santiago del Estero', 'Argentina'))
    db.session.add(Airport('SDQ', 'Aeropuerto Internacional José Francisco Peña Gómez', 'Santo Domingo', 'Santo Domingo', 'República Dominicana'))
    db.session.add(Airport('SFM', 'Aeropuerto Internacional de Sacramento', 'Sacramento', 'California', 'Estados Unidos'))
    db.session.add(Airport('SFN', 'Aeropuerto de Sauce Viejo', 'Santa Fe', 'Santa Fe', 'Argentina'))
    db.session.add(Airport('SIN', 'Aeropuerto Internacional de Singapur-Changi', 'Singapur', 'Consejo del Sudeste', 'Singapur'))
    db.session.add(Airport('SJO', 'Aeropuerto Internacional Juan Santamaría', 'San José', 'GAM GAM', 'Costa Rica'))
    db.session.add(Airport('SJZ', 'Aeropuerto de São Jorge', 'Isla de São Jorge', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('SKG', 'Aeropuerto Internacional Macedonia', 'Tesalónica', 'Macedonia Central', 'Grecia'))
    db.session.add(Airport('SLA', 'Aeropuerto Internacional de Salta Martín Miguel de Güemes', 'Ciudad de Salta', 'Salta', 'Argentina'))
    db.session.add(Airport('SMA', 'Aeropuerto de Santa Maria', 'Isla de Santa Maria', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('SNU', 'Aeropuerto Internacional Abel Santamaría', 'Santa Clara', 'Villa Clara', 'Cuba'))
    db.session.add(Airport('SUF', 'Aeropuerto Internacional de Lamezia Terme', 'Lamezia Terme', 'Lamezia Terme', 'Italia'))
    db.session.add(Airport('SVO', 'Aeropuerto Internacional de Moscú-Sheremétievo', 'Moscú', 'Moscú', 'Rusia'))
    db.session.add(Airport('SVQ', 'Aeropuerto de Sevilla', 'Sevilla', 'Andalucía', 'España'))
    db.session.add(Airport('SXB', 'Aeropuerto de Estrasburgo', 'Estrasburgo', 'Alsacia', 'Francia'))
    db.session.add(Airport('SYD', 'Aeropuerto Internacional Kingsford Smith', 'Sídney', 'Nueva Gales del Sur', 'Australia'))
    db.session.add(Airport('TER', 'Aeropuerto de Lajes', 'Isla Terceira', 'Islas Azores', 'Portugal'))
    db.session.add(Airport('TFN', 'Aeropuerto de Tenerife Norte', 'Tenerife', 'Canarias', 'España'))
    db.session.add(Airport('TFS', 'Aeropuerto de Tenerife Sur', 'Tenerife', 'Canarias', 'España'))
    db.session.add(Airport('TGD', 'Aeropuerto de Podgorica', 'Montenegro', 'Montenegro', 'Montenegro'))
    db.session.add(Airport('TGU', 'Aeropuerto de Toncontín', 'Tegucigalpa', 'Francisco Morazán', 'Honduras'))
    db.session.add(Airport('THF', 'Aeropuerto de Berlín-Tempelhof', 'Berlín', 'Berlín', 'Alemania'))
    db.session.add(Airport('TLS', 'Aeropuerto de Toulouse Blagnac', 'Toulouse', 'Occitania', 'Francia'))
    db.session.add(Airport('TLV', 'Aeropuerto Internacional Ben Gurión', 'Tel Aviv', 'Distrito Central', 'Israel'))
    db.session.add(Airport('TPE', 'Aeropuerto Internacional de Taiwán Taoyuan', 'Taipéi', 'Taoyuan', 'Taiwán [nota 10]'))
    db.session.add(Airport('TRS', 'Aeropuerto de Trieste - Friuli Venezia Giulia', 'Trieste', 'Friul-Venecia Julia', 'Italia'))
    db.session.add(Airport('TSE', 'Aeropuerto Internacional de Astaná', 'Astaná', 'Provincia de Akmola', 'Kazajistán'))
    db.session.add(Airport('TTG', 'Aeropuerto General Enrique Mosconi/Tartagal', 'Tartagal', 'Salta', 'Argentina'))
    db.session.add(Airport('TUR', 'Aeropuerto de Turku', 'Turku', 'Finlandia del Sudoeste', 'Finlandia'))
    db.session.add(Airport('UIO', 'Aeropuerto Internacional Mariscal Sucre', 'Tababela', 'Pichincha', 'Ecuador'))
    db.session.add(Airport('USH', 'Aeropuerto Internacional Malvinas Argentinas', 'Ushuaia', 'Tierra del Fuego', 'Argentina'))
    db.session.add(Airport('UZU', 'Aeropuerto de Curuzú Cuatiá', 'Curuzú Cuatiá', 'Corrientes', 'Argentina'))
    db.session.add(Airport('VCP', 'Aeropuerto de Viracopos', 'Sao Paulo', 'São Paulo', 'Brasil'))
    db.session.add(Airport('VDC', 'Aeropuerto de Vitoria da Conquista', 'Bahia', 'Bahía', 'Brasil'))
    db.session.add(Airport('VDM', 'Aeropuerto Gobernador Castello', 'Viedma', 'Río Negro', 'Argentina'))
    db.session.add(Airport('VIE', 'Aeropuerto de Viena-Schwechat', 'Viena', 'Viena', 'Austria'))
    db.session.add(Airport('VKO', 'Aeropuerto Internacional de Moscú-Vnúkovo', 'Moscú', 'Moscú', 'Rusia'))
    db.session.add(Airport('VLC', 'Aeropuerto de Valencia', 'Manises', 'Comunidad Valenciana', 'España'))
    db.session.add(Airport('VGO', 'Aeropuerto de Vigo', 'Vigo', 'Galicia', 'España'))
    db.session.add(Airport('VLL', 'Aeropuerto de Villanubla', 'Valladolid', 'Castilla y León', 'España'))
    db.session.add(Airport('VME', 'Aeropuerto de Villa Reynolds', 'Villa Mercedes', 'San Luis', 'Argentina'))
    db.session.add(Airport('VVI', 'Aeropuerto Internacional Viru Viru', 'Santa Cruz de la Sierra', 'Santa Cruz Santa Cruz', 'Bolivia'))
    db.session.add(Airport('WLG', 'Aeropuerto Internacional de Wellington', 'Wellington', 'Wellington', 'Nueva Zelanda'))
    db.session.add(Airport('XRY', 'Aeropuerto de Jerez', 'Jerez', 'Andalucía', 'España'))
    db.session.add(Airport('XPL', 'Aeropuerto Internacional de Comayagua', 'Comayagua', 'Comayagua', 'Honduras'))
    db.session.add(Airport('YFB', 'Aeropuerto de Iqaluit', 'Iqaluit', 'Nunavut', 'Canadá'))
    db.session.add(Airport('YHU', 'Aeropuerto de Montreal-Saint Hubert', 'Montreal', 'Quebec', 'Canadá'))
    db.session.add(Airport('YHZ', 'Aeropuerto Internacional de Halifax-Stanfield', 'Halifax', 'Nueva Escocia', 'Canadá'))
    db.session.add(Airport('YOW', 'Aeropuerto Internacional de Ottawa', 'Ottawa', 'Ontario', 'Canadá'))
    db.session.add(Airport('YQB', 'Aeropuerto Internacional Jean-Lesage de Quebec', 'Quebec', 'Quebec', 'Canadá'))
    db.session.add(Airport('YRB', 'Aeropuerto de Resolute Bay', 'Resolute', 'Nunavut', 'Canadá'))
    db.session.add(Airport('YUL', 'Aeropuerto Internacional Pierre Elliott Trudeau', 'Montreal', 'Quebec', 'Canadá'))
    db.session.add(Airport('YVM', 'Aeropuerto de Qikiqtarjuaq', 'Qikiqtarjuaq (en)', 'Nunavut', 'Canadá'))
    db.session.add(Airport('YVR', 'Aeropuerto Internacional de Vancouver', 'Vancouver', 'Columbia Británica', 'Canadá'))
    db.session.add(Airport('YWG', 'Aeropuerto Internacional James Armstrong Richardson', 'Winnipeg', 'Manitoba', 'Canadá'))
    db.session.add(Airport('YYY', 'Aeropuerto de Mont-Joli', 'Mont-Joli', 'Quebec', 'Canadá'))
    db.session.add(Airport('YYZ', 'Aeropuerto Internacional Toronto Pearson', 'Toronto', 'Ontario', 'Canadá'))
    db.session.add(Airport('ZAG', 'Aeropuerto de Zagreb-Pleso', 'Zagreb', 'Condado de Zagreb', 'Croacia'))
    db.session.add(Airport('ZAZ', 'Aeropuerto de Zaragoza', 'Zaragoza', 'Aragón', 'España'))
    db.session.commit()
